@startuml
skinparam useBetaStyle false
skinparam componentStyle uml1
skinparam shadowing false
'skinparam SequenceGroupHeaderFontColor #application
skinparam sequence {
    ArrowColor #222266
    LifeLineBorderColor #222266
    LifeLineBackgroundColor #222266

    ParticipantBorderColor #155AEF
    ParticipantBackgroundColor #155AEF
    ParticipantFontName Arial
    ParticipantFontSize 15
    ParticipantFontColor #ffffff

    BoxBackgroundColor #application
    BoxBorderColor #ffffff

    GroupHeaderFontColor #ffffff
    GroupBackgroundColor #155AEF
    GroupBorderColor #155AEF

    ActorBorderColor #155AEF
    ActorBackgroundColor #155AEF
    ActorFontColor #155AEF
}

box "MOSIP"
actor Admin as admin
participant  "Partner management services" as pms
end box

box "CA"
participant  "CA" as ca
participant  "Intermediate CA" as subca
end box

participant  "ABIS partner" as abis

note over abis
Creds:
* ActiveMQ
* Mosip creds
end note

admin -> pms: Create new policy group
admin -> pms: Create policy
admin -> pms: Approve policy
admin -> pms:

@enduml